### PR TITLE
changed do_propeganda

### LINKED ISSUE #24: do_propeganda is spelled incorrectly
The function `do_propeganda` in swskills.c should be renamed `do_propaganda`. This includes all references to it in tables.c and mud.h, including strings... and any other references not mentioned here.

NOTE: This will require the ~~commands.dat~~ skills.dat to be updated to point to the new name for the propaganda skill.

### PR DESCRIPTION
**Pull request by svenkat19**
Went through all the .c and .h files in src and updated do_propeganda to do_propaganda.  In the description, you had mentioned to change the "commands.dat" file as well but I was unable to find it. I went through all the .dat files and found only one of them needed the change. Let me know if I have missed out on anything. Cheers!!

### CODE REVIEW

**Comment by jcmcbeth** [comment]
Looks good at first glance. I did mix up that do_propaganda is a skill and not a command, so skills.dat is probably the correct place.

I will test this later and merge the PR if there are no issues found.

Thanks for looking into this.

**Comment by jcmcbeth** [comment]
@svenkat19 Turns out that propaganda is spelled wrong everywhere. That's my mistake for not checking other places since I was thinking it was a command instead of a skill.

image

Could you also update those references too for this? Also, there is one additional reference to "progeganda" in skills.dat.

**Comment by svenkat19** [comment]
I have changed the spelling error in all the above mentioned files. I accidently removed the assignment as well😬. Anyway, please let me know if there are anymore changes😁.

**Review by jcmcbeth — APPROVED** [review]
Works great! Thanks.

image

**Pull request merged**
